# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.6.5
_src_path: https://github.com/jupyterlab/extension-template
advanced: false
author_email: konrad.jelen+github@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupyterlab_advanced_paste_content_extension
project_short_description: Jupyterlab extension that captures pasted content (text,
    file, graphics file / screenshot etc) and copies it to the current folder and
    in the receiving end (txt file, md file, python file or terminal). Extension will
    use different handlers to dedice how to handle the content
python_name: jupyterlab_advanced_paste_content_extension
repository: https://github.com/stellarshenson/jupyterlab_advanced_paste_content_extension
test: true

